project_name: "Gateway Autentika"
project_sigla: "gateway_autentika"
project_path: "/gateway_autentika"
project_path_test: "/gateway_autentika-test"
project_port: "8088:8082"
project_env:
  dev:
    ENVIRONMENT: DEV_ENVIRONMENT
    AUTENTIKA_AUTHORIZATION_ENDPOINT: DEV_AUTENTIKA_AUTHORIZATION_ENDPOINT
    AUTENTIKA_GW_CONFIG_ENDPOINT: DEV_AUTENTIKA_GW_CONFIG_ENDPOINT
  qual:
    ENVIRONMENT: QUAL_ENVIRONMENT
    AUTENTIKA_AUTHORIZATION_ENDPOINT: QUAL_AUTENTIKA_AUTHORIZATION_ENDPOINT
    AUTENTIKA_GW_CONFIG_ENDPOINT: QUAL_AUTENTIKA_GW_CONFIG_ENDPOINT
  prod:
    ENVIRONMENT: PROD_ENVIRONMENT
    AUTENTIKA_AUTHORIZATION_ENDPOINT: PROD_AUTENTIKA_AUTHORIZATION_ENDPOINT
    AUTENTIKA_GW_CONFIG_ENDPOINT: PROD_AUTENTIKA_GW_CONFIG_ENDPOINT
